---

- name: Set application parameters SF3
  template:
    src: templates/parameters.yml
    dest: "{{ project_root }}/app/config/parameters.yml"
  when: project_type == 'default' and symfony_version == '3'

- name: Set application parameters SF2
  template:
    src: templates/parameters-sf2.yml
    dest: "{{ project_root }}/app/config/parameters.yml"
  when: project_type == 'default' and symfony_version == '2'

- name: Set application parameters SF3 EVENT
  template:
    src: templates/parameters-event.yml
    dest: "{{ project_root }}/app/config/parameters.yml"
  when: project_type == 'event'

- name: Set symfony_console.
  set_fact: symfony_console="{{ project_root }}/{{ console_command }} --env={{ env }}"

- name: Add jwt directory
  file: path={{project_root}}/var/jwt state=directory mode=0755
  when: project_type == 'default' and symfony_version == '3'

- name: Add jwt private key
  copy: content="{{ jwt_private_pem }}" dest={{ project_root }}/var/jwt/private.pem
  when: project_type == 'default' and symfony_version == '3'

- name: Add jwt public key
  copy: content="{{ jwt_public_pem }}" dest={{ project_root }}/var/jwt/public.pem
  when: project_type == 'default' and symfony_version == '3'
  
- name: Replace cache and log directory Symfony2
  shell: |
    sed -i -e "s/\$this->rootDir.'\/'.\$this->environment.'/'\/dev\/shm/g" {{ project_root }}/app/AppKernel.php
  when: build == 'vagrant' and symfony_version == '2'

- name: Replace cache and log directory Symfony3
  shell: |
    sed -i -e "s/dirname(__DIR__).'\//'\/dev\/shm\//g" {{ project_root }}/app/AppKernel.php
  when: build == 'vagrant' and symfony_version == '3'