- name: Set permission for logs and cache folders.
  acl:
    path: /dev/shm/var
    entity: www-data
    etype: user
    permissions: rwx
    recursive: true
    state: present
  when: build == 'vagrant'

- name: Set permission for logs and cache folders.
  acl:
    path: "{{ project_root }}/var"
    entity: www-data
    etype: user
    permissions: rwx
    recursive: true
    state: present
  when: build == 'aws'