- name: Set permission for logs and cache folders.
  acl:
    path: /dev/shm/var
    entity: www-data
    etype: user
    permissions: rwx
    recursive: true
    state: present
  when: build == 'vagrant' and (symfony_version == '3' or symfony_version == '4')

- name: chmod var log & cache folder
  file: path=/dev/shm/var state=directory mode=0777 recurse=yes
  when: project_type == 'default' and symfony_version == '4'

- name: Set permission for cache folders.
  acl:
    path: /dev/shm/cache
    entity: www-data
    etype: user
    permissions: rwx
    recursive: true
    state: present
  when: (build == 'vagrant' and symfony_version == '2') 

- name: Set permission for logs folders.
  acl:
    path: /dev/shm/logs
    entity: www-data
    etype: user
    permissions: rwx
    recursive: true
    state: present
  when: build == 'vagrant' and symfony_version == '2'

- name: Set permission for logs and cache folders.
  acl:
    path: "{{ project_root }}/var"
    entity: www-data
    etype: user
    permissions: rwx
    recursive: true
    state: present
  when: build == 'aws' and (symfony_version == '3' or symfony_version == '4')

- name: Set permission for cache folders.
  acl:
    path: "{{ project_root }}/app/cache"
    entity: www-data
    etype: user
    permissions: rwx
    recursive: true
    state: present
  when: build == 'aws' and symfony_version == '2'

- name: Set permission for logs folders.
  acl:
    path: "{{ project_root }}/app/logs"
    entity: www-data
    etype: user
    permissions: rwx
    recursive: true
    state: present
  when: build == 'aws' and symfony_version == '2'