---

- name: Copy PGSQL Databases to System
  copy:
    src: db/{{ item.name }}.pgsql
    dest: /tmp
  with_items:
  - '{{postgresql_databases}}'
  when: build == 'vagrant' and project_type == 'default' and symfony_version == '3'

- name: Import Databases
  shell: export PGPASSWORD='{{ db_pass }}' && psql -U {{ db_user }} -h {{ db_host }} -d {{ db_name }} < /tmp/{{ item.name }}.pgsql
  with_items:
  - '{{postgresql_databases}}'
  when: build == 'vagrant' and project_type == 'default' and symfony_version == '3'

- name: Copy Databases to System
  copy:
    src: db/{{ item.name }}
    dest: /var/www
  with_items:
  - '{{mysql_db}}'
  when: build == 'vagrant' and symfony_version == '2'

- name: Import Databases
  mysql_db:
    state: import
    name: "{{ item.name }}"
    target: /tmp/{{ item.name }}
  with_items:
  - '{{mysql_db}}'
  when: build == 'vagrant' and symfony_version == '2'

- name: Schema Update.
  action: shell {{php_path}} {{symfony_console}} doctrine:schema:update --force
  run_once: true
  when: build == 'vagrant' and project_type == 'default'

- name: Copy Redis Databases to System
  copy:
    src: db/dump.rdb
    dest: /tmp
  when: build == 'vagrant' and project_type == 'default' and symfony_version == '3' 

- name: import bdd Redis
  shell: |
      rdis-cli -a {{ redis_requirepass }} shutdown
      cd /var/redis/6379
      rm -f dump.rdb
      mv /tmp/dump.rdb /var/redis/6379
      chown redis:redis /var/redis/6379/dump.rdb
      /etc/init.d/redis_6379 start
      redis-cli -a {{ redis_requirepass }} BGREWRITEAOF
      redis-cli -a {{ redis_requirepass }} info | grep aof_rewrite_in_progress
  when: build == 'vagrant' and project_type == 'default' and symfony_version == '3'