- name: create .aws
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: ubuntu
    group: ubuntu
  with_items:
    - "/home/ubuntu/.aws"

- name: Set aws crendetials
  template:
    src: templates/aws-credentials.yml
    dest: "/home/ubuntu/.aws/credentials"
  when: project_type == 'default' and symfony_version == '3'