- cron:
    name: "update jerseys value"
    minute: "1"
    hour: "1"
    user: root
    job: "cd /var/www/sf-back/ && sudo bin/console sf:championship:jersey:update_jerseys_value"
    cron_file: update_jerseys_value
- cron:
    name: "update jerseys popularity"
    minute: "20"
    hour: "1"
    user: root
    job: "cd /var/www/sf-back/ && sudo bin/console sf:championship:jersey:update_jerseys_popularity"
    cron_file: update_jerseys_popularity
- cron:
    name: "update jerseys form"
    minute: "40"
    hour: "1"
    user: root
    job: "cd /var/www/sf-back/ && sudo bin/console sf:championship:jersey:update_jerseys_form"
    cron_file: update_jerseys_form
- cron:
    name: "access token google"
    minute: "*/30"
    user: root
    job: "cd /var/www/sf-back/ && sudo bin/console sf:core:google:refresh_token"
    cron_file: google_access_token
- cron:
    name: cloudwatch-memory-asg-job
    minute: "*/5"
    user: root
    job: "/tmp/aws-scripts-mon/mon-put-instance-data.pl --mem-util --mem-used --mem-avail --auto-scaling=only"
    cron_file: cloudwatch_asg_memory
- cron:
    name: cloudwatch-disk-space-asg-job
    minute: "*/5"
    user: root
    job: "/tmp/aws-scripts-mon/mon-put-instance-data.pl --disk-path=/ --disk-space-util --disk-space-avail --disk-space-used --auto-scaling=only"
    cron_file: cloudwatch_asg_space_disk